---
- name: Installing Apacke Tomcat Server
  hosts: test
  become: true
  become_user: root
  tasks: 
   - name: Installing Apache Tomcat
     get_url: 
        url: http://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz
        dest: /usr/local/
     tags: apache

   - name: unarchive
     unarchive:
       src: /usr/local/apache-tomcat-9.0.30.tar.gz
       dest: /usr/local/
       remote_src: yes
     tags: unarchive
 
   - name: Moving  /usr/local/apache-tomcat-9.0.30 to /usr/local/tomcat9
     command: mv /usr/local/apache-tomcat-9.0.30 /usr/local/tomcat9
     tags: move

   - name: 
     lineinfile: 
       path: /home/ansadm/.bashrc 
       insertafter: EOF
       line: "export CATALINA_HOME=/usr/local/tomcat9"
     tags: insert

   - name: source bashrc
     shell: source /home/ansadm/.bashrc && /usr/local/tomcat9/bin/startup.sh
     tags: source

   - name: running apache tomact server
     command: /usr/local/tomcat9/bin/startup.sh
     tags: ats

